package com.university.backend.entity;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class UserTest {

    // ==========================================
    // CONSTRUCTOR TESTS
    // ==========================================

    // TEST 1: Create user with default constructor - should work
    @Test
    public void createUser_DefaultConstructor_ShouldWork() {
        // Step 1: Create user with default constructor
        User user = new User();
        
        // Step 2: Check that object was created
        assertNotNull(user);
        
        // Step 3: Check that fields are initially null (as expected)
        assertNull(user.getId());
        assertNull(user.getEmail());
        assertNull(user.getPassword());
        assertNull(user.getRole());
    }

    // TEST 2: Create user with 3-parameter constructor - should work
    @Test
    public void createUser_ThreeParameterConstructor_ShouldWork() {
        // Step 1: Create user with email, password, role
        User user = new User("john@test.com", "password123", "STUDENT");
        
        // Step 2: Check that object was created
        assertNotNull(user);
        
        // Step 3: Check that fields were set correctly
        assertEquals("john@test.com", user.getEmail());
        assertEquals("password123", user.getPassword());
        assertEquals("STUDENT", user.getRole());
        
        // Step 4: ID should be null (auto-generated by database)
        assertNull(user.getId());
    }

    // TEST 3: Create user with 4-parameter constructor - should work
    @Test
    public void createUser_FourParameterConstructor_ShouldWork() {
        // Step 1: Create user with all fields including ID
        User user = new User(1L, "jane@test.com", "mypassword", "PROFESSOR");
        
        // Step 2: Check that all fields were set correctly
        assertEquals(1L, user.getId());
        assertEquals("jane@test.com", user.getEmail());
        assertEquals("mypassword", user.getPassword());
        assertEquals("PROFESSOR", user.getRole());
    }

    // ==========================================
    // GETTER AND SETTER TESTS
    // ==========================================

    // TEST 4: Test email getter and setter - should work
    @Test
    public void emailGetterSetter_ValidEmail_ShouldWork() {
        // Step 1: Create user
        User user = new User();
        
        // Step 2: Set email using setter
        user.setEmail("test@example.com");
        
        // Step 3: Get email using getter and verify
        assertEquals("test@example.com", user.getEmail());
    }

    // TEST 5: Test password getter and setter - should work
    @Test
    public void passwordGetterSetter_ValidPassword_ShouldWork() {
        // Step 1: Create user
        User user = new User();
        
        // Step 2: Set password using setter
        user.setPassword("securePassword123");
        
        // Step 3: Get password using getter and verify
        assertEquals("securePassword123", user.getPassword());
    }

    // TEST 6: Test role getter and setter - should work
    @Test
    public void roleGetterSetter_ValidRole_ShouldWork() {
        // Step 1: Create user
        User user = new User();
        
        // Step 2: Set role using setter
        user.setRole("ADMIN");
        
        // Step 3: Get role using getter and verify
        assertEquals("ADMIN", user.getRole());
    }

    // TEST 7: Test ID getter and setter - should work
    @Test
    public void idGetterSetter_ValidId_ShouldWork() {
        // Step 1: Create user
        User user = new User();
        
        // Step 2: Set ID using setter
        user.setId(42L);
        
        // Step 3: Get ID using getter and verify
        assertEquals(42L, user.getId());
    }

    // ==========================================
    // FIELD VALIDATION TESTS
    // ==========================================

    // TEST 8: Test valid email formats - should work
    @Test
    public void setEmail_ValidFormats_ShouldWork() {
        User user = new User();
        
        // Test various valid email formats
        user.setEmail("simple@test.com");
        assertEquals("simple@test.com", user.getEmail());
        
        user.setEmail("user.name@domain.co.uk");
        assertEquals("user.name@domain.co.uk", user.getEmail());
        
        user.setEmail("test123@university.edu");
        assertEquals("test123@university.edu", user.getEmail());
    }

    // TEST 9: Test different role types - should work
    @Test
    public void setRole_ValidRoles_ShouldWork() {
        User user = new User();
        
        // Test STUDENT role
        user.setRole("STUDENT");
        assertEquals("STUDENT", user.getRole());
        
        // Test PROFESSOR role
        user.setRole("PROFESSOR");
        assertEquals("PROFESSOR", user.getRole());
        
        // Test ADMIN role
        user.setRole("ADMIN");
        assertEquals("ADMIN", user.getRole());
    }

    // TEST 10: Test password requirements - should work
    @Test
    public void setPassword_ValidPasswords_ShouldWork() {
        User user = new User();
        
        // Test short password
        user.setPassword("123");
        assertEquals("123", user.getPassword());
        
        // Test long password
        user.setPassword("thisIsAVeryLongPasswordWithManyCharacters123!");
        assertEquals("thisIsAVeryLongPasswordWithManyCharacters123!", user.getPassword());
        
        // Test password with special characters
        user.setPassword("P@ssw0rd!");
        assertEquals("P@ssw0rd!", user.getPassword());
    }

    // ==========================================
    // EDGE CASE TESTS
    // ==========================================

    // TEST 11: Test null email handling - should work (but not recommended)
    @Test
    public void setEmail_NullValue_ShouldWork() {
        User user = new User();
        
        // Set null email (entity allows it, database will reject it)
        user.setEmail(null);
        
        // Should store null value in object
        assertNull(user.getEmail());
    }

    // TEST 12: Test empty email handling - should work
    @Test
    public void setEmail_EmptyValue_ShouldWork() {
        User user = new User();
        
        // Set empty email
        user.setEmail("");
        
        // Should store empty string
        assertEquals("", user.getEmail());
        assertTrue(user.getEmail().isEmpty());
    }

    // TEST 13: Test null password handling - should work (but not recommended)
    @Test
    public void setPassword_NullValue_ShouldWork() {
        User user = new User();
        
        // Set null password
        user.setPassword(null);
        
        // Should store null value in object
        assertNull(user.getPassword());
    }

    // TEST 14: Test null role handling - should work (but not recommended)
    @Test
    public void setRole_NullValue_ShouldWork() {
        User user = new User();
        
        // Set null role
        user.setRole(null);
        
        // Should store null value in object
        assertNull(user.getRole());
    }

    // ==========================================
    // BUSINESS LOGIC TESTS
    // ==========================================

    // TEST 15: Test complete user creation workflow - should work
    @Test
    public void createCompleteUser_AllFields_ShouldWork() {
        // Step 1: Create user with constructor
        User user = new User("admin@university.com", "adminPass123", "ADMIN");
        
        // Step 2: Set ID (simulating database assignment)
        user.setId(100L);
        
        // Step 3: Verify all fields are correct
        assertEquals(100L, user.getId());
        assertEquals("admin@university.com", user.getEmail());
        assertEquals("adminPass123", user.getPassword());
        assertEquals("ADMIN", user.getRole());
        
        // Step 4: Verify object is complete
        assertNotNull(user.getId());
        assertNotNull(user.getEmail());
        assertNotNull(user.getPassword());
        assertNotNull(user.getRole());
    }

    // TEST 16: Test user field updates - should work
    @Test
    public void updateUserFields_ExistingUser_ShouldWork() {
        // Step 1: Create initial user
        User user = new User("old@email.com", "oldPassword", "STUDENT");
        user.setId(1L);
        
        // Step 2: Update fields
        user.setEmail("new@email.com");
        user.setPassword("newPassword123");
        user.setRole("PROFESSOR");
        
        // Step 3: Verify updates worked
        assertEquals(1L, user.getId()); // ID should remain the same
        assertEquals("new@email.com", user.getEmail());
        assertEquals("newPassword123", user.getPassword());
        assertEquals("PROFESSOR", user.getRole());
    }

    // TEST 17: Test role case sensitivity - should work
    @Test
    public void setRole_CaseSensitive_ShouldWork() {
        User user = new User();
        
        // Test lowercase role
        user.setRole("student");
        assertEquals("student", user.getRole());
        
        // Test uppercase role
        user.setRole("STUDENT");
        assertEquals("STUDENT", user.getRole());
        
        // Test mixed case role
        user.setRole("Student");
        assertEquals("Student", user.getRole());
        
        // Note: In real application, you might want to standardize case
    }

    // TEST 18: Test email case handling - should work
    @Test
    public void setEmail_CaseHandling_ShouldWork() {
        User user = new User();
        
        // Test uppercase email
        user.setEmail("TEST@EXAMPLE.COM");
        assertEquals("TEST@EXAMPLE.COM", user.getEmail());
        
        // Test lowercase email
        user.setEmail("test@example.com");
        assertEquals("test@example.com", user.getEmail());
        
        // Note: In real application, you might want to normalize email case
    }

    // TEST 19: Test special characters in password - should work
    @Test
    public void setPassword_SpecialCharacters_ShouldWork() {
        User user = new User();
        
        // Test password with various special characters
        String specialPassword = "P@$$w0rd!#$%^&*()_+-=[]{}|;:,.<>?";
        user.setPassword(specialPassword);
        
        assertEquals(specialPassword, user.getPassword());
    }

    // TEST 20: Test very long email - should work (entity level)
    @Test
    public void setEmail_VeryLongEmail_ShouldWork() {
        User user = new User();
        
        // Create very long email (might be rejected by database constraints)
        String longEmail = "verylongemailaddressthatmightexceedtypicaldatabaselimits@verylongdomainname.com";
        user.setEmail(longEmail);
        
        assertEquals(longEmail, user.getEmail());
        
        // Note: Database might have length constraints that would reject this
    }
}